<?php
/**
 * @var Magento\Framework\View\Element\Template $block
 * @var Mgn\Notification\ViewModel\Post $notificationModel
 *
 */
$notificationModel = $block->getData('notification_post');
$moduleData = $notificationModel->getDetail();
?>


<div class="blog-post-list">
    <h1>Welcome to the Promotion Notification</h1>
    <?php foreach ($moduleData as $data): ?>
        <p>ID: <?= $data->getId() ?></p>
        <p>Description: <?= $data->getDescription() ?></p>
        <p>Promotion Name: <?= $data->getPromotionName() ?></p>
        <p>Start Date: <?= $data->getStartDate() ?></p>
        <p>End Date: <?= $data->getEndDate() ?></p>
    <?php endforeach; ?>
</div>
